// <auto-generated />
using System;
using DoAn.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAn.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("Seq_BaoCaoHT_ID");

            modelBuilder.HasSequence<int>("Seq_BinhLuan_ID");

            modelBuilder.HasSequence<int>("Seq_CanhBao_ID");

            modelBuilder.HasSequence<int>("Seq_DoiCuuHo_ID");

            modelBuilder.HasSequence<int>("Seq_KhoVatTu_ID");

            modelBuilder.HasSequence<int>("Seq_NguoiDung_ID");

            modelBuilder.HasSequence<int>("Seq_NguonLuc_ID");

            modelBuilder.HasSequence<int>("Seq_NhiemVuCuuHo_ID");

            modelBuilder.HasSequence<int>("Seq_QuyenGop_ID");

            modelBuilder.HasSequence<int>("Seq_ThongBao_ID");

            modelBuilder.HasSequence<int>("Seq_TinhNguyenVien_ID");

            modelBuilder.HasSequence<int>("Seq_TinTuc_ID");

            modelBuilder.HasSequence<int>("Seq_VaiTro_ID");

            modelBuilder.Entity("DoAn.Server.Models.BaoCaoHienTruong", b =>
                {
                    b.Property<string>("MaBaoCaoHT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'BCHT' + FORMAT(NEXT VALUE FOR Seq_BaoCaoHT_ID, '000')");

                    b.Property<float?>("KinhDo")
                        .HasColumnType("real");

                    b.Property<string>("LinkHinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThietHai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiBaoCao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MucDoThietHai")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("ViDo")
                        .HasColumnType("real");

                    b.HasKey("MaBaoCaoHT");

                    b.HasIndex("MaNguoiBaoCao");

                    b.HasIndex("KinhDo", "ViDo");

                    b.ToTable("BaoCaoHienTruong");
                });

            modelBuilder.Entity("DoAn.Server.Models.BinhLuan", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR Seq_BinhLuan_ID");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTinTuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBinhLuan");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTinTuc");

                    b.ToTable("BinhLuan");
                });

            modelBuilder.Entity("DoAn.Server.Models.CanhBao", b =>
                {
                    b.Property<string>("MaCanhBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'CB' + FORMAT(NEXT VALUE FOR Seq_CanhBao_ID, '000')");

                    b.Property<float?>("BanKinhAnhHuong")
                        .HasColumnType("real");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<float?>("KinhDo")
                        .HasColumnType("real");

                    b.Property<string>("LoaiCanhBao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiDuyet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MucDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("ViDo")
                        .HasColumnType("real");

                    b.Property<string>("VungAnhHuong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCanhBao");

                    b.HasIndex("MaNguoiDuyet");

                    b.HasIndex("MaNguoiTao");

                    b.HasIndex("TrangThai");

                    b.ToTable("CanhBao");
                });

            modelBuilder.Entity("DoAn.Server.Models.DoiCuuHo", b =>
                {
                    b.Property<string>("MaDoiCuuHo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'DCH' + FORMAT(NEXT VALUE FOR Seq_DoiCuuHo_ID, '000')");

                    b.Property<string>("MaNguoiQuanLy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDoiCuuHo");

                    b.HasIndex("MaNguoiQuanLy");

                    b.ToTable("DoiCuuHo");
                });

            modelBuilder.Entity("DoAn.Server.Models.KhoVatTu", b =>
                {
                    b.Property<string>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'K' + FORMAT(NEXT VALUE FOR Seq_KhoVatTu_ID, '000')");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiQuanLy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKho");

                    b.HasIndex("MaNguoiQuanLy");

                    b.ToTable("KhoVatTu");
                });

            modelBuilder.Entity("DoAn.Server.Models.NguoiDung", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'U' + FORMAT(NEXT VALUE FOR Seq_NguoiDung_ID, '000')");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<byte>("LoginAttempts")
                        .HasColumnType("tinyint");

                    b.Property<string>("MaVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("DoAn.Server.Models.NguonLucCuuTro", b =>
                {
                    b.Property<string>("MaNguonLuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'NL' + FORMAT(NEXT VALUE FOR Seq_NguonLuc_ID, '000')");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiQuanLyKho")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNguonLuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguonLuc");

                    b.HasIndex("MaNguoiQuanLyKho");

                    b.ToTable("NguonLucCuuTro");
                });

            modelBuilder.Entity("DoAn.Server.Models.NhiemVuCuuHo", b =>
                {
                    b.Property<string>("MaNhiemVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'NV' + FORMAT(NEXT VALUE FOR Seq_NhiemVuCuuHo_ID, '000')");

                    b.Property<string>("MaDoiCuuHo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaNhiemVu");

                    b.HasIndex("MaNguoiTao");

                    b.HasIndex("TrangThai");

                    b.ToTable("NhiemVuCuuHo");
                });

            modelBuilder.Entity("DoAn.Server.Models.PhanCongNhiemVu", b =>
                {
                    b.Property<string>("MaNhiemVu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDoiCuuHo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhiemVu", "MaDoiCuuHo");

                    b.HasIndex("MaDoiCuuHo");

                    b.ToTable("PhanCongNhiemVu");
                });

            modelBuilder.Entity("DoAn.Server.Models.PhanCongTinhNguyenVien", b =>
                {
                    b.Property<string>("MaTinhNguyenVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNhiemVu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinhNguyenVien", "MaNhiemVu");

                    b.HasIndex("MaNhiemVu");

                    b.ToTable("PhanCongTinhNguyenVien");
                });

            modelBuilder.Entity("DoAn.Server.Models.QuyenGop", b =>
                {
                    b.Property<string>("MaQuyenGop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'QG' + FORMAT(NEXT VALUE FOR Seq_QuyenGop_ID, '000')");

                    b.Property<string>("LoaiQuyenGop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiQuyenGop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNguonLuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayQuyenGop")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaQuyenGop");

                    b.HasIndex("MaNguoiQuyenGop");

                    b.HasIndex("MaNguonLuc");

                    b.ToTable("QuyenGop");
                });

            modelBuilder.Entity("DoAn.Server.Models.ThongBaoCaNhan", b =>
                {
                    b.Property<string>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'TB' + FORMAT(NEXT VALUE FOR Seq_ThongBao_ID, '000')");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiThongBao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaNguoiNhan");

                    b.ToTable("ThongBaoCaNhan");
                });

            modelBuilder.Entity("DoAn.Server.Models.TinTuc", b =>
                {
                    b.Property<string>("MaTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'TT' + FORMAT(NEXT VALUE FOR Seq_TinTuc_ID, '000')");

                    b.Property<string>("AnhBia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<string>("MaNguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinTuc");

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("TinTuc");
                });

            modelBuilder.Entity("DoAn.Server.Models.TinhNguyenVien", b =>
                {
                    b.Property<string>("MaTinhNguyenVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'TNV' + FORMAT(NEXT VALUE FOR Seq_TinhNguyenVien_ID, '000')");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinhNguyenVien");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("TinhNguyenVien");
                });

            modelBuilder.Entity("DoAn.Server.Models.VaiTro", b =>
                {
                    b.Property<string>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("'VT' + FORMAT(NEXT VALUE FOR Seq_VaiTro_ID, '00')");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("DoAn.Server.Models.VatTuTrongKho", b =>
                {
                    b.Property<string>("MaNguonLuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKho")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaNguonLuc", "MaKho");

                    b.HasIndex("MaKho");

                    b.ToTable("VatTuTrongKho");
                });

            modelBuilder.Entity("DoAn.Server.Models.BaoCaoHienTruong", b =>
                {
                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiBaoCao")
                        .WithMany()
                        .HasForeignKey("MaNguoiBaoCao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiBaoCao");
                });

            modelBuilder.Entity("DoAn.Server.Models.BinhLuan", b =>
                {
                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAn.Server.Models.TinTuc", "TinTuc")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaTinTuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("TinTuc");
                });

            modelBuilder.Entity("DoAn.Server.Models.CanhBao", b =>
                {
                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("MaNguoiDuyet")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDuyet");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("DoAn.Server.Models.DoiCuuHo", b =>
                {
                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiQuanLy")
                        .WithMany()
                        .HasForeignKey("MaNguoiQuanLy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiQuanLy");
                });

            modelBuilder.Entity("DoAn.Server.Models.KhoVatTu", b =>
                {
                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiQuanLy")
                        .WithMany()
                        .HasForeignKey("MaNguoiQuanLy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiQuanLy");
                });

            modelBuilder.Entity("DoAn.Server.Models.NguoiDung", b =>
                {
                    b.HasOne("DoAn.Server.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("DoAn.Server.Models.NguonLucCuuTro", b =>
                {
                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiQuanLyKho")
                        .WithMany()
                        .HasForeignKey("MaNguoiQuanLyKho")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiQuanLyKho");
                });

            modelBuilder.Entity("DoAn.Server.Models.NhiemVuCuuHo", b =>
                {
                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("DoAn.Server.Models.PhanCongNhiemVu", b =>
                {
                    b.HasOne("DoAn.Server.Models.DoiCuuHo", "DoiCuuHo")
                        .WithMany("PhanCongNhiemVus")
                        .HasForeignKey("MaDoiCuuHo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Server.Models.NhiemVuCuuHo", "NhiemVu")
                        .WithMany("PhanCongNhiemVus")
                        .HasForeignKey("MaNhiemVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoiCuuHo");

                    b.Navigation("NhiemVu");
                });

            modelBuilder.Entity("DoAn.Server.Models.PhanCongTinhNguyenVien", b =>
                {
                    b.HasOne("DoAn.Server.Models.NhiemVuCuuHo", "NhiemVu")
                        .WithMany("PhanCongTinhNguyenViens")
                        .HasForeignKey("MaNhiemVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Server.Models.TinhNguyenVien", "TinhNguyenVien")
                        .WithMany("PhanCongNhiemVus")
                        .HasForeignKey("MaTinhNguyenVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhiemVu");

                    b.Navigation("TinhNguyenVien");
                });

            modelBuilder.Entity("DoAn.Server.Models.QuyenGop", b =>
                {
                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiQuyenGop")
                        .WithMany()
                        .HasForeignKey("MaNguoiQuyenGop")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DoAn.Server.Models.NguonLucCuuTro", "NguonLuc")
                        .WithMany()
                        .HasForeignKey("MaNguonLuc")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiQuyenGop");

                    b.Navigation("NguonLuc");
                });

            modelBuilder.Entity("DoAn.Server.Models.ThongBaoCaNhan", b =>
                {
                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("MaNguoiNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("DoAn.Server.Models.TinTuc", b =>
                {
                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("DoAn.Server.Models.TinhNguyenVien", b =>
                {
                    b.HasOne("DoAn.Server.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAn.Server.Models.VatTuTrongKho", b =>
                {
                    b.HasOne("DoAn.Server.Models.KhoVatTu", "KhoVatTu")
                        .WithMany("VatTuTrongKhos")
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn.Server.Models.NguonLucCuuTro", "NguonLuc")
                        .WithMany("VatTuTrongKhos")
                        .HasForeignKey("MaNguonLuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoVatTu");

                    b.Navigation("NguonLuc");
                });

            modelBuilder.Entity("DoAn.Server.Models.DoiCuuHo", b =>
                {
                    b.Navigation("PhanCongNhiemVus");
                });

            modelBuilder.Entity("DoAn.Server.Models.KhoVatTu", b =>
                {
                    b.Navigation("VatTuTrongKhos");
                });

            modelBuilder.Entity("DoAn.Server.Models.NguonLucCuuTro", b =>
                {
                    b.Navigation("VatTuTrongKhos");
                });

            modelBuilder.Entity("DoAn.Server.Models.NhiemVuCuuHo", b =>
                {
                    b.Navigation("PhanCongNhiemVus");

                    b.Navigation("PhanCongTinhNguyenViens");
                });

            modelBuilder.Entity("DoAn.Server.Models.TinTuc", b =>
                {
                    b.Navigation("BinhLuans");
                });

            modelBuilder.Entity("DoAn.Server.Models.TinhNguyenVien", b =>
                {
                    b.Navigation("PhanCongNhiemVus");
                });

            modelBuilder.Entity("DoAn.Server.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
